# Generated by Django 4.1 on 2022-09-10 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starredideas',
            name='star_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.star'),
        ),
        migrations.AlterField(
            model_name='starredideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
