# Generated by Django 4.1 on 2022-09-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_starredideas_star_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starredideas',
            name='star_object',
        ),
        migrations.AddField(
            model_name='starredideas',
            name='idea_object',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.idea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='star',
            name='related_idea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.idea'),
        ),
    ]
