# Generated by Django 4.1 on 2022-09-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starredideas',
            old_name='idea_object',
            new_name='related_idea',
        ),
    ]
